//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:16:04 PM EST 
//

package com.grndctl.model.aircraftrep;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="turbulence_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="turbulence_intensity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="turbulence_base_ft_msl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="turbulence_top_ft_msl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="turbulence_freq" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "turbulence_condition")
public class TurbulenceCondition {

    @XmlAttribute(name = "turbulence_type")
    protected String turbulenceType;
    @XmlAttribute(name = "turbulence_intensity")
    protected String turbulenceIntensity;
    @XmlAttribute(name = "turbulence_base_ft_msl")
    protected Integer turbulenceBaseFtMsl;
    @XmlAttribute(name = "turbulence_top_ft_msl")
    protected Integer turbulenceTopFtMsl;
    @XmlAttribute(name = "turbulence_freq")
    protected String turbulenceFreq;

    /**
     * Gets the value of the turbulenceType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTurbulenceType() {
        return turbulenceType;
    }

    /**
     * Sets the value of the turbulenceType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTurbulenceType(String value) {
        this.turbulenceType = value;
    }

    /**
     * Gets the value of the turbulenceIntensity property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTurbulenceIntensity() {
        return turbulenceIntensity;
    }

    /**
     * Sets the value of the turbulenceIntensity property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTurbulenceIntensity(String value) {
        this.turbulenceIntensity = value;
    }

    /**
     * Gets the value of the turbulenceBaseFtMsl property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getTurbulenceBaseFtMsl() {
        return turbulenceBaseFtMsl;
    }

    /**
     * Sets the value of the turbulenceBaseFtMsl property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setTurbulenceBaseFtMsl(Integer value) {
        this.turbulenceBaseFtMsl = value;
    }

    /**
     * Gets the value of the turbulenceTopFtMsl property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getTurbulenceTopFtMsl() {
        return turbulenceTopFtMsl;
    }

    /**
     * Sets the value of the turbulenceTopFtMsl property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setTurbulenceTopFtMsl(Integer value) {
        this.turbulenceTopFtMsl = value;
    }

    /**
     * Gets the value of the turbulenceFreq property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTurbulenceFreq() {
        return turbulenceFreq;
    }

    /**
     * Sets the value of the turbulenceFreq property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTurbulenceFreq(String value) {
        this.turbulenceFreq = value;
    }

}
