//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:17:02 PM EST 
//

package com.grndctl.model.gairmet;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="min_ft_msl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="max_ft_msl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "fzl_altitude")
public class FzlAltitude {

    @XmlAttribute(name = "min_ft_msl")
    protected Integer minFtMsl;
    @XmlAttribute(name = "max_ft_msl")
    protected Integer maxFtMsl;

    /**
     * Gets the value of the minFtMsl property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getMinFtMsl() {
        return minFtMsl;
    }

    /**
     * Sets the value of the minFtMsl property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setMinFtMsl(Integer value) {
        this.minFtMsl = value;
    }

    /**
     * Gets the value of the maxFtMsl property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getMaxFtMsl() {
        return maxFtMsl;
    }

    /**
     * Sets the value of the maxFtMsl property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setMaxFtMsl(Integer value) {
        this.maxFtMsl = value;
    }

}
