//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:16:35 PM EST 
//

package com.grndctl.model.airsigmet;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}raw_text" minOccurs="0"/>
 *         &lt;element ref="{}valid_time_from" minOccurs="0"/>
 *         &lt;element ref="{}valid_time_to" minOccurs="0"/>
 *         &lt;element ref="{}altitude" minOccurs="0"/>
 *         &lt;element ref="{}movement_dir_degrees" minOccurs="0"/>
 *         &lt;element ref="{}movement_speed_kt" minOccurs="0"/>
 *         &lt;element ref="{}hazard" minOccurs="0"/>
 *         &lt;element ref="{}airsigmet_type" minOccurs="0"/>
 *         &lt;element ref="{}area" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "rawText", "validTimeFrom", "validTimeTo",
        "altitude", "movementDirDegrees", "movementSpeedKt", "hazard",
        "airsigmetType", "area" })
@XmlRootElement(name = "AIRSIGMET")
public class AIRSIGMET {

    @XmlElement(name = "raw_text")
    protected String rawText;
    @XmlElement(name = "valid_time_from")
    protected String validTimeFrom;
    @XmlElement(name = "valid_time_to")
    protected String validTimeTo;
    protected Altitude altitude;
    @XmlElement(name = "movement_dir_degrees")
    protected BigInteger movementDirDegrees;
    @XmlElement(name = "movement_speed_kt")
    protected BigInteger movementSpeedKt;
    protected Hazard hazard;
    @XmlElement(name = "airsigmet_type")
    protected String airsigmetType;
    protected List<Area> area;

    /**
     * Gets the value of the rawText property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRawText() {
        return rawText;
    }

    /**
     * Sets the value of the rawText property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRawText(String value) {
        this.rawText = value;
    }

    /**
     * Gets the value of the validTimeFrom property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValidTimeFrom() {
        return validTimeFrom;
    }

    /**
     * Sets the value of the validTimeFrom property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValidTimeFrom(String value) {
        this.validTimeFrom = value;
    }

    /**
     * Gets the value of the validTimeTo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValidTimeTo() {
        return validTimeTo;
    }

    /**
     * Sets the value of the validTimeTo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValidTimeTo(String value) {
        this.validTimeTo = value;
    }

    /**
     * Gets the value of the altitude property.
     * 
     * @return possible object is {@link Altitude }
     * 
     */
    public Altitude getAltitude() {
        return altitude;
    }

    /**
     * Sets the value of the altitude property.
     * 
     * @param value
     *            allowed object is {@link Altitude }
     * 
     */
    public void setAltitude(Altitude value) {
        this.altitude = value;
    }

    /**
     * Gets the value of the movementDirDegrees property.
     * 
     * @return possible object is {@link java.math.BigInteger }
     * 
     */
    public BigInteger getMovementDirDegrees() {
        return movementDirDegrees;
    }

    /**
     * Sets the value of the movementDirDegrees property.
     * 
     * @param value
     *            allowed object is {@link java.math.BigInteger }
     * 
     */
    public void setMovementDirDegrees(BigInteger value) {
        this.movementDirDegrees = value;
    }

    /**
     * Gets the value of the movementSpeedKt property.
     * 
     * @return possible object is {@link java.math.BigInteger }
     * 
     */
    public BigInteger getMovementSpeedKt() {
        return movementSpeedKt;
    }

    /**
     * Sets the value of the movementSpeedKt property.
     * 
     * @param value
     *            allowed object is {@link java.math.BigInteger }
     * 
     */
    public void setMovementSpeedKt(BigInteger value) {
        this.movementSpeedKt = value;
    }

    /**
     * Gets the value of the hazard property.
     * 
     * @return possible object is {@link Hazard }
     * 
     */
    public Hazard getHazard() {
        return hazard;
    }

    /**
     * Sets the value of the hazard property.
     * 
     * @param value
     *            allowed object is {@link Hazard }
     * 
     */
    public void setHazard(Hazard value) {
        this.hazard = value;
    }

    /**
     * Gets the value of the airsigmetType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAirsigmetType() {
        return airsigmetType;
    }

    /**
     * Sets the value of the airsigmetType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAirsigmetType(String value) {
        this.airsigmetType = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the area property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Area }
     * 
     * 
     */
    public List<Area> getArea() {
        if (area == null) {
            area = new ArrayList<Area>();
        }
        return this.area;
    }

}
