/**
 * This file is part of grndctl.
 *
 * grndctl is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * grndctl is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with grndctl.  If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:18:46 PM EST 
//

package com.grndctl.model.taf;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="icing_intensity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="icing_min_alt_ft_agl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="icing_max_alt_ft_agl" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "icing_condition")
public class IcingCondition {

    @XmlAttribute(name = "icing_intensity")
    protected String icingIntensity;
    @XmlAttribute(name = "icing_min_alt_ft_agl")
    protected Integer icingMinAltFtAgl;
    @XmlAttribute(name = "icing_max_alt_ft_agl")
    protected Integer icingMaxAltFtAgl;

    /**
     * Gets the value of the icingIntensity property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIcingIntensity() {
        return icingIntensity;
    }

    /**
     * Sets the value of the icingIntensity property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIcingIntensity(String value) {
        this.icingIntensity = value;
    }

    /**
     * Gets the value of the icingMinAltFtAgl property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getIcingMinAltFtAgl() {
        return icingMinAltFtAgl;
    }

    /**
     * Sets the value of the icingMinAltFtAgl property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setIcingMinAltFtAgl(Integer value) {
        this.icingMinAltFtAgl = value;
    }

    /**
     * Gets the value of the icingMaxAltFtAgl property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getIcingMaxAltFtAgl() {
        return icingMaxAltFtAgl;
    }

    /**
     * Sets the value of the icingMaxAltFtAgl property.
     * 
     * @param value
     *            allowed object is {@link Integer }
     * 
     */
    public void setIcingMaxAltFtAgl(Integer value) {
        this.icingMaxAltFtAgl = value;
    }

}
