//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:18:46 PM EST 
//

package com.grndctl.model.taf;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}raw_text" minOccurs="0"/>
 *         &lt;element ref="{}station_id" minOccurs="0"/>
 *         &lt;element ref="{}issue_time" minOccurs="0"/>
 *         &lt;element ref="{}bulletin_time" minOccurs="0"/>
 *         &lt;element ref="{}valid_time_from" minOccurs="0"/>
 *         &lt;element ref="{}valid_time_to" minOccurs="0"/>
 *         &lt;element ref="{}remarks" minOccurs="0"/>
 *         &lt;element ref="{}latitude" minOccurs="0"/>
 *         &lt;element ref="{}longitude" minOccurs="0"/>
 *         &lt;element ref="{}elevation_m" minOccurs="0"/>
 *         &lt;element ref="{}forecast" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "rawText", "stationId", "issueTime",
        "bulletinTime", "validTimeFrom", "validTimeTo", "remarks", "latitude",
        "longitude", "elevationM", "forecast" })
@XmlRootElement(name = "TAF")
public class TAF {

    @XmlElement(name = "raw_text")
    protected String rawText;
    @XmlElement(name = "station_id")
    protected String stationId;
    @XmlElement(name = "issue_time")
    protected String issueTime;
    @XmlElement(name = "bulletin_time")
    protected String bulletinTime;
    @XmlElement(name = "valid_time_from")
    protected String validTimeFrom;
    @XmlElement(name = "valid_time_to")
    protected String validTimeTo;
    protected String remarks;
    protected Float latitude;
    protected Float longitude;
    @XmlElement(name = "elevation_m")
    protected Float elevationM;
    protected List<Forecast> forecast;

    /**
     * Gets the value of the rawText property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRawText() {
        return rawText;
    }

    /**
     * Sets the value of the rawText property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRawText(String value) {
        this.rawText = value;
    }

    /**
     * Gets the value of the stationId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * Sets the value of the stationId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setStationId(String value) {
        this.stationId = value;
    }

    /**
     * Gets the value of the issueTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIssueTime() {
        return issueTime;
    }

    /**
     * Sets the value of the issueTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIssueTime(String value) {
        this.issueTime = value;
    }

    /**
     * Gets the value of the bulletinTime property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBulletinTime() {
        return bulletinTime;
    }

    /**
     * Sets the value of the bulletinTime property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBulletinTime(String value) {
        this.bulletinTime = value;
    }

    /**
     * Gets the value of the validTimeFrom property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValidTimeFrom() {
        return validTimeFrom;
    }

    /**
     * Sets the value of the validTimeFrom property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValidTimeFrom(String value) {
        this.validTimeFrom = value;
    }

    /**
     * Gets the value of the validTimeTo property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValidTimeTo() {
        return validTimeTo;
    }

    /**
     * Sets the value of the validTimeTo property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setValidTimeTo(String value) {
        this.validTimeTo = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return possible object is {@link Float }
     * 
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *            allowed object is {@link Float }
     * 
     */
    public void setLatitude(Float value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return possible object is {@link Float }
     * 
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *            allowed object is {@link Float }
     * 
     */
    public void setLongitude(Float value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the elevationM property.
     * 
     * @return possible object is {@link Float }
     * 
     */
    public Float getElevationM() {
        return elevationM;
    }

    /**
     * Sets the value of the elevationM property.
     * 
     * @param value
     *            allowed object is {@link Float }
     * 
     */
    public void setElevationM(Float value) {
        this.elevationM = value;
    }

    /**
     * Gets the value of the forecast property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the forecast property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getForecast().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Forecast }
     * 
     * 
     */
    public List<Forecast> getForecast() {
        if (forecast == null) {
            forecast = new ArrayList<Forecast>();
        }
        return this.forecast;
    }

}
